### ISSUE TITLE
SDKMAN 5.5.9+231 is BROKEN

### ISSUE THREAD

**Issue by brianjohnsen** [sdkman/sdkman-cli#587]
Version SDKMAN 5.5.9+231 is broken.
Makes any command respond with 'Stop! XXXX is not a valid candidate.'

Uninstalling and reinstalling sdkman does not solve the problem.

System:
Ubuntu, kernel: 4.10.0-22-generic

**Comment by lordcrekit** [comment]
See the recent slack conversation for details.

Specifically this post:
> Michael Amster
> @mamsterla
> 14:58
> Found it - the call to /candidates/all gives an error:
> curl -s "${SDKMAN_CURRENT_API}/candidates/all"
> That should actually return a comma delimited list of candidates

**Comment by nbkhope** [comment]
Everything I do gives that message. I even posted on Stack Overflow, https://stackoverflow.com/questions/44507424/sdkman-5-5-9231-says-package-is-not-a-valid-candidate-on-macos
I guess it's a bug?

**Comment by josephswanson-wf** [comment]
seeing the same on OSX and Ubuntu Trusty

**Comment by lordcrekit** [comment]
fixed as of 2017-06-13 14:52:00?

**Comment by josephswanson-wf** [comment]
working for me

**Comment by brianjohnsen** [comment]
Working for me too.

**Comment by bonespiked** [comment]
Did you have to do anything for it to work - I tried flushing candidates, and I'm still getting same error....

**Comment by josephswanson-wf** [comment]
`rm -rf ~/.sdkman` and a fresh install got me back online on OSX.. trying to fetch candidates seemed to recreate broken links

my ubuntu setup was part of a build process, so once the API was back online, installing from scratch worked as intended

**Comment by marc0der** [comment]
Sdkman 5.5.9+231 is not BROKEN.

**Comment by nbkhope** [comment]
It seeems problem was on the server side. You don't need to reinstall Sdkman to fix the issue. Just flush the candidates and RESTART your terminal.

```
sdk flush candidates
# then restart your terminal
```

**Comment by marc0der** [comment]
Exactly, the candidates endpoint was returning bad responses due to a malformed entry in the database.
